sudo: required
services:
  - docker
before_install:
  - docker build -t pantbinod/multi-container-app -f ./client/Dockerfile.dev
script:
  - docker run pantbinod/multi-container-app npm test -- --coverage